name: Build

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target to build'
        required: false
        default: ''
        type: string
      debug:
        description: 'Debug mode'
        required: false
        default: false
        type: boolean
  schedule:
    - cron: '0 19 * * 5' # 03:00 CST/Beijing every Saturday

permissions: write-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: an7581
            arch: arm64
            source: https://github.com/web1n/immortalwrt
            branch: xg-040g-md
          - target: ipq60xx
            arch: arm64
            source: https://github.com/VIKINGYFY/immortalwrt
            branch: main
          - target: ipq807x
            arch: arm64
            source: https://github.com/VIKINGYFY/immortalwrt
            branch: main
          - target: mt7621
            arch: mips
            source: https://github.com/immortalwrt/immortalwrt
            branch: master
    uses: ./.github/workflows/reusable-build.yml
    with:
      target: ${{ matrix.target }}
      arch: ${{ matrix.arch }}
      source: ${{ matrix.source }}
      branch: ${{ matrix.branch }}
      debug: ${{ inputs.debug == true }}
      selected_target: ${{ inputs.target }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && !inputs.debug
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./release-files
          merge-multiple: true
      - name: Generate Tag & Name
        id: vars
        run: |
          echo "TAG=$(date -u '+%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT
          echo "CURRENT_DATE=$(date -u '+%y%m%d%H%M')" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Build - ${{ steps.vars.outputs.CURRENT_DATE }}"
          tag_name: ${{ steps.vars.outputs.TAG }}
          files: |
            ./release-files/*
