name: Delete old releases and workflow runs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

permissions: write-all

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          releases_keep_latest: 3
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 3
          gh_token: ${{ secrets.GITHUB_TOKEN }}
